
--drop TRIGGER CLIENTS_BI_TRG;

create table CLIENTS
(
    CLIENT_ID NUMBER PRIMARY KEY,
    CLIENT_NAME VARCHAR2(128),
    CLIENT_ADDRESS VARCHAR2(256)
);

CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1 
    MAXVALUE 999999999999;

CREATE OR REPLACE TRIGGER CLIENTS_BI_TRG
    BEFORE 
    INSERT
    ON CLIENTS
    FOR EACH ROW    
DECLARE
BEGIN
   :NEW.CLIENT_ID := CLIENT_SEQ.NEXTVAL;
END;

